=== jhbruhn/fmes/Abgabe/src/resources/territorium.dtd
<!ELEMENT territorium (attributes, feld)>
<!ELEMENT attributes (fahrtRichtung, feldSpalteBug, feldSpalteHeck, feldReiheHeck, feldReiheBug, territoriumSpecialFinishNummer, startSpalteHeck, startSpalteBug, startReiheHeck, startReiheBug, resizeable, objectResizedWidth, objectResizedHeigth, entfernungBreiteDesSpielFeldes, entfernungHoeheDesSpielFeldes, beleuchtung, batterieAnBord, feldhoehe, feldbreite, nachfolgeLevel)>
<!ELEMENT feld (feldZeile*)>
<!ELEMENT feldZeile (feldElement*)>

<!ELEMENT feldElement EMPTY>
<!ATTLIST feldElement
	value CDATA #REQUIRED
>

<!ELEMENT fahrtRichtung EMPTY>
<!ATTLIST fahrtRichtung
	value CDATA #REQUIRED
>

<!ELEMENT feldSpalteBug EMPTY>
<!ATTLIST feldSpalteBug
	value CDATA #REQUIRED
>

<!ELEMENT feldSpalteHeck EMPTY>
<!ATTLIST feldSpalteHeck
	value CDATA #REQUIRED
>

<!ELEMENT feldReiheHeck EMPTY>
<!ATTLIST feldReiheHeck
	value CDATA #REQUIRED
>

<!ELEMENT feldReiheBug EMPTY>
<!ATTLIST feldReiheBug
	value CDATA #REQUIRED
>

<!ELEMENT territoriumSpecialFinishNummer EMPTY>
<!ATTLIST territoriumSpecialFinishNummer
	value CDATA #REQUIRED
>

<!ELEMENT startSpalteHeck EMPTY>
<!ATTLIST startSpalteHeck
	value CDATA #REQUIRED
>

<!ELEMENT startSpalteBug EMPTY>
<!ATTLIST startSpalteBug
	value CDATA #REQUIRED
>

<!ELEMENT startReiheHeck EMPTY>
<!ATTLIST startReiheHeck
	value CDATA #REQUIRED
>

<!ELEMENT startReiheBug EMPTY>
<!ATTLIST startReiheBug
	value CDATA #REQUIRED
>

<!ELEMENT resizeable EMPTY>
<!ATTLIST resizeable
	value CDATA #REQUIRED
>

<!ELEMENT objectResizedWidth EMPTY>
<!ATTLIST objectResizedWidth
	value CDATA #REQUIRED
>

<!ELEMENT objectResizedHeigth EMPTY>
<!ATTLIST objectResizedHeigth
	value CDATA #REQUIRED
>

<!ELEMENT entfernungBreiteDesSpielFeldes EMPTY>
<!ATTLIST entfernungBreiteDesSpielFeldes
	value CDATA #REQUIRED
>

<!ELEMENT entfernungHoeheDesSpielFeldes EMPTY>
<!ATTLIST entfernungHoeheDesSpielFeldes
	value CDATA #REQUIRED
>

<!ELEMENT beleuchtung EMPTY>
<!ATTLIST beleuchtung
	value CDATA #REQUIRED
>

<!ELEMENT batterieAnBord EMPTY>
<!ATTLIST batterieAnBord
	value CDATA #REQUIRED
>

<!ELEMENT feldhoehe EMPTY>
<!ATTLIST feldhoehe
	value CDATA #REQUIRED
>

<!ELEMENT feldbreite EMPTY>
<!ATTLIST feldbreite
	value CDATA #REQUIRED
>

<!ELEMENT nachfolgeLevel EMPTY>
<!ATTLIST nachfolgeLevel
	value CDATA #REQUIRED
>

=== jhbruhn/fmes/src/resources/UBootDefault.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE territorium SYSTEM "../src/resources/territorium.dtd">
<territorium>
<attributes>
<fahrtRichtung id="fahrtRichtung" value="Ost"></fahrtRichtung>
<feldSpalteBug value="4"></feldSpalteBug>
<feldSpalteHeck value="3"></feldSpalteHeck>
<feldReiheHeck value="4"></feldReiheHeck>
<feldReiheBug value="4"></feldReiheBug>
<territoriumSpecialFinishNummer value="9000"></territoriumSpecialFinishNummer>
<startSpalteHeck value="0"></startSpalteHeck>
<startSpalteBug value="0"></startSpalteBug>
<startReiheHeck value="0"></startReiheHeck>
<startReiheBug value="0"></startReiheBug>
<resizeable value="true"></resizeable>
<objectResizedWidth value="50.0"></objectResizedWidth>
<objectResizedHeigth value="39.02597402597402"></objectResizedHeigth>
<entfernungBreiteDesSpielFeldes value="0.0"></entfernungBreiteDesSpielFeldes>
<entfernungHoeheDesSpielFeldes value="0.0"></entfernungHoeheDesSpielFeldes>
<beleuchtung value="true"></beleuchtung>
<batterieAnBord value="false"></batterieAnBord>
<feldhoehe value="15"></feldhoehe>
<feldbreite value="10"></feldbreite>
<nachfolgeLevel value="0"></nachfolgeLevel>
</attributes>
<feld><feldZeile><feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
</feldZeile>
<feldZeile><feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
</feldZeile>
<feldZeile><feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
</feldZeile>
<feldZeile><feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Felsen"></feldElement>
<feldElement value="Batterie"></feldElement>
<feldElement value="LeuchtFelsen"></feldElement>
<feldElement value="ZielFeld"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
</feldZeile>
<feldZeile><feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
</feldZeile>
<feldZeile><feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
</feldZeile>
<feldZeile><feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
</feldZeile>
<feldZeile><feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
</feldZeile>
<feldZeile><feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
</feldZeile>
<feldZeile><feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Hai"></feldElement>
</feldZeile>
<feldZeile><feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
</feldZeile>
<feldZeile><feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
</feldZeile>
<feldZeile><feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
</feldZeile>
<feldZeile><feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
</feldZeile>
<feldZeile><feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
<feldElement value="Leer"></feldElement>
</feldZeile>
</feld>
</territorium>
